name: Automerge PR

on:
  push:
    branches-ignore:
      - master

jobs:
  set-auto-merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set to automerge
        uses: heitorpolidoro/auto-merge@master
        with:
          personal_access_token: ${{ secrets.PAT }}
          allowed_users: heitorpolidoro